targets = ["x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-freebsd"]

[[files]]
local = "resources/agent.json.pkg"
remote = "ETC/intecture/agent.json"

[scripts]
build = "sed 's~<CFGPATH>~/usr/local/etc/intecture~' resources/agent.json > resources/agent.json.pkg"
