#!/bin/sh

. /etc/rc.subr

name=inagent
rcvar=inagent_enable
load_rc_config $name

command="/usr/local/bin/${name}"
pidfile="/var/run/${name}.pid"
required_files=/usr/local/etc/intecture/agent.json

start_cmd=inagent_start
stop_postcmd=inagent_cleanup

inagent_start() {
    echo "Starting inagent."
    /usr/bin/touch ${pidfile}
    /usr/sbin/daemon -cf -p ${pidfile} ${command}
}

inagent_cleanup() {
    /bin/rm -f ${pidfile}
}

run_rc_command "$1"
